name: Test DevOpsForAI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install scipy==1.0.0 scikit-learn==0.19.1 numpy==1.14.5 pandas==0.23.1 azureml-sdk[notebooks]
    - name: Run data test
      run: |
        python code/testing/data_test.py data/diabetes.csv
    - name: Run scoring test
      run: |
        python code/scoring/score.py