name: Test DevOpsForAI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        bash environment_setup/install_requirements.sh
    - name: Run data test
      run: |
        python code/testing/data_test.py data/diabetes.csv
    - name: Train model
      run: |
        python code/training/train.py
    - name: Run scoring test
      run: |
        python code/scoring/score.py